name: uni_auth
description: "UniAuth is a Flutter package designed to handle authentication modules in Flutter applications. It integrates various authentication services, primarily focusing on Firebase Auth for authentication and Unifonic for sending and verifying OTPs (One-Time Passwords)."
version: 1.0.0
repository: https://github.com/abdallah128128/uni_auth

environment:
  sdk: ">=3.3.2 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.1
  #* firebase
  firebase_core: ^2.30.0
  firebase_auth: ^4.19.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
