// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvZ8ktbRxu-ujY75-i1fUgHpM9jwySopI',
    appId: '1:407479976818:web:f6a2041333e531f63c13eb',
    messagingSenderId: '407479976818',
    projectId: 'test-uniauth',
    authDomain: 'test-uniauth.firebaseapp.com',
    storageBucket: 'test-uniauth.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtFFEB3MwKc3zPx8TZd8VIlmiuPFfKkmw',
    appId: '1:407479976818:android:efb7769d7a190ad43c13eb',
    messagingSenderId: '407479976818',
    projectId: 'test-uniauth',
    storageBucket: 'test-uniauth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2yB2y3zkn06WT1QwROBMuA6FH1OmdKuw',
    appId: '1:407479976818:ios:5c462f0f2a3fa6223c13eb',
    messagingSenderId: '407479976818',
    projectId: 'test-uniauth',
    storageBucket: 'test-uniauth.appspot.com',
    iosBundleId: 'com.example.example',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2yB2y3zkn06WT1QwROBMuA6FH1OmdKuw',
    appId: '1:407479976818:ios:5c462f0f2a3fa6223c13eb',
    messagingSenderId: '407479976818',
    projectId: 'test-uniauth',
    storageBucket: 'test-uniauth.appspot.com',
    iosBundleId: 'com.example.example',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvZ8ktbRxu-ujY75-i1fUgHpM9jwySopI',
    appId: '1:407479976818:web:d0fb8990e1f770e93c13eb',
    messagingSenderId: '407479976818',
    projectId: 'test-uniauth',
    authDomain: 'test-uniauth.firebaseapp.com',
    storageBucket: 'test-uniauth.appspot.com',
  );
}
